name: Deploy MkDocs

on:
  push:
    branches:
      - main # 如果您的主分支叫 master，请改成 master

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11' # 设定 Python 版本

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install mkdocs-material

      - name: Deploy to GitHub Pages
        run: mkdocs gh-deploy --force